openapi: 3.0.0
info:
  title: "RespirAR API"
  version: "1.0.0"
  description: "RespirAR API Documentation"
servers:
  - url: "http://localhost:8080/"
    description: "Local server"
paths:    
  /api/v1/healthcheck:
    get:
      summary: Get health status information
      description: Returns a JSON object with health status information.
      tags:
        - Healthcheck
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The health status of the application
                    example: "Healthy"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Internal Server Error"
  /api/v1/requests:
    get:
      summary: Obtains requests.
      description: Obtains requests according to parameters.
      tags:
        - Requests
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Access token for authentication.
        - in: query
          name: pageSize
          schema:
            type: integer
          description: The number of items to return per page.
        - in: query
          name: page
          schema:
            type: integer
          description: The page number to return.
        - in: query
          name: name
          schema:
            type: string
          description: The station name to filter by.
        - in: query
          name: serialNumber
          schema:
            type: string
          description: The serial number to filter by.
        - in: query
          name: status
          schema:
            type: string
          description: The request status to filter by.
        - in: query
          name: date
          schema:
            type: string
          description: The creation date to filter by.
      responses:
        200:
          description: A list of requests with optional pagination.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      description: Unique identifier of the request.
                      example: "64612f41b0a9b6ebef6a0e66"
                    serial_number:
                      type: string
                      description: Serial number of the station.
                      example: "8edsf23489"
                    name:
                      type: string
                      description: Name of the station.
                      example: "Air-Quality-Station"
                    longitude:
                      type: number
                      format: float
                      description: Longitude of the station's location.
                      example: -159.6969448413211
                    latitude:
                      type: number
                      format: float
                      description: Latitude of the station's location.
                      example: 21.371452961552126
                    brand:
                      type: string
                      description: Brand of the station.
                      example: Huawei
                    model:
                      type: string
                      description: Model of the station.
                      example: L17GYT-G
                    status:
                      type: string
                      enum:
                        - PENDING
                        - APPROVED
                        - REJECTED
                      description: Status of the request.
                    created_by:
                      type: integer
                      description: Identifier of the user who created the request.
                      example: 2
                    created_at:
                      type: string
                      format: date-time
                      description: Date and time when the request was created.
                    approved_by:
                      type: integer
                      nullable: true
                      description: Identifier of the user who approved the request.
                      example: 1
                    approved_at:
                      type: string
                      format: date-time
                      nullable: true
                      description: Date and time when the request was approved.
        401:
          description: Unauthorized Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Unathorized"
        403:
          description: Forbbiden Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Forbbiden"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Internal Server Error"
  /users/{userId}/requests:
    post:
      summary: Create a request for a user.
      description: Creates a new request for the specified user.
      tags:
        - Requests
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: The ID of the user.
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Access token for authentication.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                serial_number:
                  type: string
                  description: Serial number of the station.
                  example: 8edsg2348112aJ
                name:
                  type: string
                  description: Name of the station.
                  example: Air-Quality-Station
                longitude:
                  type: number
                  format: float
                  description: Longitude of the station's location.
                  example: -159.6969448413211
                latitude:
                  type: number
                  format: float
                  description: Latitude of the station's location.
                  example: 21.371452961552126
                brand:
                  type: string
                  description: Brand of the station.
                  example: Huawei
                model:
                  type: string
                  description: Model of the station.
                  example: L17GYT-G
      responses:
        201:
          description: The created request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    description: Unique identifier of the request.
                    example: "64612f41b0a9b6ebef6a0e66"
                  serial_number:
                    type: string
                    description: Serial number of the station.
                    example: "8edsf23489"
                  name:
                    type: string
                    description: Name of the station.
                    example: "Air-Quality-Station"
                  longitude:
                    type: number
                    format: float
                    description: Longitude of the station's location.
                    example: -159.6969448413211
                  latitude:
                    type: number
                    format: float
                    description: Latitude of the station's location.
                    example: 21.371452961552126
                  brand:
                    type: string
                    description: Brand of the station.
                    example: Huawei
                  model:
                    type: string
                    description: Model of the station.
                    example: L17GYT-G
                  status:
                    type: string
                    enum:
                      - PENDING
                      - APPROVED
                      - REJECTED
                    description: Status of the request.
                  created_by:
                    type: integer
                    description: Identifier of the user who created the request.
                    example: 2
                  created_at:
                    type: string
                    format: date-time
                    description: Date and time when the request was created.
                  approved_by:
                    type: integer
                    nullable: true
                    description: Identifier of the user who approved the request.
                    example: 1
                  approved_at:
                    type: string
                    format: date-time
                    nullable: true
                    description: Date and time when the request was approved.
        400:
          description: Unauthorized Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Bad Request"
        401:
          description: Unauthorized Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Unathorized"
        403:
          description: Forbbiden Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Forbbiden"
        404:
          description: Not Found Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Not Found"
        409:
          description: Conflict Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Conflict"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Internal Server Error"
  /api/v1/stations:
    get:
      summary: Obtains stations.
      description: Obtains stations according to parameters.
      tags:
        - Stations
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Access token for authentication.
        - in: query
          name: pageSize
          schema:
            type: integer
          description: The number of items to return per page.
        - in: query
          name: page
          schema:
            type: integer
          description: The page number to return.
        - in: query
          name: name
          schema:
            type: string
          description: The station name to filter by.
        - in: query
          name: serialNumber
          schema:
            type: string
          description: The serial number to filter by.
        - in: query
          name: status
          schema:
            type: string
          description: The request status to filter by.
        - in: query
          name: date
          schema:
            type: string
          description: The creation date to filter by.
      responses:
        200:
          description: A list of stations with optional pagination.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      description: Unique identifier of the request.
                      example: "64612f41b0a9b6ebef6a0e66"
                    serial_number:
                      type: string
                      description: Serial number of the station.
                      example: "8edsf23489"
                    name:
                      type: string
                      description: Name of the station.
                      example: "Air-Quality-Station"
                    longitude:
                      type: number
                      format: float
                      description: Longitude of the station's location.
                      example: -159.6969448413211
                    latitude:
                      type: number
                      format: float
                      description: Latitude of the station's location.
                      example: 21.371452961552126
                    brand:
                      type: string
                      description: Brand of the station.
                      example: Huawei
                    model:
                      type: string
                      description: Model of the station.
                      example: L17GYT-G
                    status:
                      type: string
                      enum:
                        - PENDING
                        - APPROVED
                        - REJECTED
                      description: Status of the request.
                    created_by:
                      type: integer
                      description: Identifier of the user who created the request.
                      example: 2
                    created_at:
                      type: string
                      format: date-time
                      description: Date and time when the request was created.
        401:
          description: Unauthorized Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Unathorized"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Internal Server Error"
  /users/{userId}/requests/{requestId}/accept:
    patch:
      summary: Accept a request.
      description: Accepts the specified request for the user.
      tags:
        - Requests
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: The ID of the user.
        - in: path
          name: requestId
          schema:
            type: string
          required: true
          description: The ID of the request.
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Access token for authentication.
      responses:
        200:
          description: The created request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    description: Unique identifier of the request.
                    example: "64612f41b0a9b6ebef6a0e66"
                  serial_number:
                    type: string
                    description: Serial number of the station.
                    example: "8edsf23489"
                  name:
                    type: string
                    description: Name of the station.
                    example: "Air-Quality-Station"
                  longitude:
                    type: number
                    format: float
                    description: Longitude of the station's location.
                    example: -159.6969448413211
                  latitude:
                    type: number
                    format: float
                    description: Latitude of the station's location.
                    example: 21.371452961552126
                  brand:
                    type: string
                    description: Brand of the station.
                    example: Huawei
                  model:
                    type: string
                    description: Model of the station.
                    example: L17GYT-G
                  status:
                    type: string
                    enum:
                      - PENDING
                      - APPROVED
                      - REJECTED
                    description: Status of the request.
                  created_by:
                    type: integer
                    description: Identifier of the user who created the request.
                    example: 2
                  created_at:
                    type: string
                    format: date-time
                    description: Date and time when the request was created.
                  approved_by:
                    type: integer
                    nullable: true
                    description: Identifier of the user who approved the request.
                    example: 1
                  approved_at:
                    type: string
                    format: date-time
                    nullable: true
                    description: Date and time when the request was approved.
        401:
          description: Unauthorized.
        404:
          description: User or request not found.
        409:
          description: Request has an invalid status or station already exists.
        500:
          description: Internal server error.


