version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: